version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      # - ./mysql:/var/lib/mysql
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wpsite
    ports:
      - "8002:3306"

#  phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     container_name: phpmyadmin
#     # restart: always
#     environment:
#       - PMA_HOST=db
#       - MYSQL_ROOT_PASSWORD=password
#       - PMA_USER=root
#       - PMA_PASSWORD=password
#     networks:
#       - wpsite
#     ports:
#       - "8001:80"

  wordpress:
    build: ./
    container_name: wordpress
    image: wordpress:5.0.0-php7.2-apache
    depends_on:
      - db
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wpsite
    ports:
      - "80:80"
networks:
  wpsite:

volumes:
  db_data: